//
// ApiErrorDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiErrorDetail: Sendable, Codable, Hashable {

    /** 機器可讀錯誤碼（invalid_body / invalid_id / invalid_input / unknown_exercise / unknown_template / unknown_plan_workout / unknown_plan_set / not_found / id_conflict / in_use / db_unavailable / internal） */
    public var code: String
    public var message: String

    public init(code: String, message: String) {
        self.code = code
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(message, forKey: .message)
    }
}

