//
// Equipment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** 器材（DB 存英文 token，中文顯示由前端對應） */
public enum Equipment: String, Sendable, Codable, CaseIterable {
    case barbell = "barbell"
    case dumbbell = "dumbbell"
    case kettlebell = "kettlebell"
    case hexBar = "hex_bar"
    case machine = "machine"
    case cable = "cable"
    case band = "band"
    case bodyweight = "bodyweight"
    case other = "other"
}
