//
// ExerciseInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ExerciseInput: Sendable, Codable, Hashable {

    public static let nameRule = StringRule(minLength: 1, maxLength: 100, pattern: nil)
    /** 可選；客戶端可自帶 UUID（供日後 local-first 同步）。僅建立時有效，更新時忽略。 */
    public var id: UUID?
    public var name: String
    public var muscleGroup: MuscleGroup
    public var equipment: Equipment
    public var description: String?

    public init(id: UUID? = nil, name: String, muscleGroup: MuscleGroup, equipment: Equipment, description: String? = nil) {
        self.id = id
        self.name = name
        self.muscleGroup = muscleGroup
        self.equipment = equipment
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case muscleGroup = "muscle_group"
        case equipment
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(muscleGroup, forKey: .muscleGroup)
        try container.encode(equipment, forKey: .equipment)
        try container.encodeIfPresent(description, forKey: .description)
    }
}


extension ExerciseInput: Identifiable {}
