//
// Exercise.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Exercise: Sendable, Codable, Hashable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 100, pattern: nil)
    public var id: UUID
    public var name: String
    public var muscleGroup: MuscleGroup
    public var description: String?
    public var createdBy: UUID
    public var createdAt: Date
    public var updatedAt: Date

    public init(id: UUID, name: String, muscleGroup: MuscleGroup, description: String?, createdBy: UUID, createdAt: Date, updatedAt: Date) {
        self.id = id
        self.name = name
        self.muscleGroup = muscleGroup
        self.description = description
        self.createdBy = createdBy
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case muscleGroup = "muscle_group"
        case description
        case createdBy = "created_by"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(muscleGroup, forKey: .muscleGroup)
        try container.encode(description, forKey: .description)
        try container.encode(createdBy, forKey: .createdBy)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


extension Exercise: Identifiable {}
