//
// MuscleGroup.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** 肌群（DB 存英文 token，中文顯示由前端對應） */
public enum MuscleGroup: String, Sendable, Codable, CaseIterable {
    case chest = "chest"
    case back = "back"
    case legs = "legs"
    case shoulders = "shoulders"
    case arms = "arms"
    case core = "core"
    case functional = "functional"
    case other = "other"
}
