//
// PlanWorkout.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PlanWorkout: Sendable, Codable, Hashable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 50, pattern: nil)
    public static let orderIndexRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var id: UUID
    public var userId: UUID
    /** null＝單獨排課（不屬任何菜單） */
    public var planId: UUID?
    public var name: String?
    public var orderIndex: Int
    public var status: PlanWorkoutStatus
    /** null＝循環（依 order_index 輪替）；有值＝指定日 */
    public var date: String?
    /** 範本來源（複製建立時記錄） */
    public var fromSpecsPlanWorkoutId: UUID?
    public var createdAt: Date
    public var updatedAt: Date
    public var sets: [TargetSet]

    public init(id: UUID, userId: UUID, planId: UUID?, name: String?, orderIndex: Int, status: PlanWorkoutStatus, date: String?, fromSpecsPlanWorkoutId: UUID?, createdAt: Date, updatedAt: Date, sets: [TargetSet]) {
        self.id = id
        self.userId = userId
        self.planId = planId
        self.name = name
        self.orderIndex = orderIndex
        self.status = status
        self.date = date
        self.fromSpecsPlanWorkoutId = fromSpecsPlanWorkoutId
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.sets = sets
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case userId = "user_id"
        case planId = "plan_id"
        case name
        case orderIndex = "order_index"
        case status
        case date
        case fromSpecsPlanWorkoutId = "from_specs_plan_workout_id"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case sets
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(userId, forKey: .userId)
        try container.encode(planId, forKey: .planId)
        try container.encode(name, forKey: .name)
        try container.encode(orderIndex, forKey: .orderIndex)
        try container.encode(status, forKey: .status)
        try container.encode(date, forKey: .date)
        try container.encode(fromSpecsPlanWorkoutId, forKey: .fromSpecsPlanWorkoutId)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(sets, forKey: .sets)
    }
}


extension PlanWorkout: Identifiable {}
