//
// PlanSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PlanSummary: Sendable, Codable, Hashable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 50, pattern: nil)
    public var id: UUID
    public var userId: UUID
    public var name: String
    public var description: String?
    public var status: PlanStatus
    /** 範本來源（從範本複製建立時記錄） */
    public var fromSpecsPlanId: UUID?
    public var createdAt: Date
    public var updatedAt: Date

    public init(id: UUID, userId: UUID, name: String, description: String?, status: PlanStatus, fromSpecsPlanId: UUID?, createdAt: Date, updatedAt: Date) {
        self.id = id
        self.userId = userId
        self.name = name
        self.description = description
        self.status = status
        self.fromSpecsPlanId = fromSpecsPlanId
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case userId = "user_id"
        case name
        case description
        case status
        case fromSpecsPlanId = "from_specs_plan_id"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(userId, forKey: .userId)
        try container.encode(name, forKey: .name)
        try container.encode(description, forKey: .description)
        try container.encode(status, forKey: .status)
        try container.encode(fromSpecsPlanId, forKey: .fromSpecsPlanId)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


extension PlanSummary: Identifiable {}
