//
// PlanStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** 個人菜單狀態 */
public enum PlanStatus: String, Sendable, Codable, CaseIterable {
    case active = "active"
    case completed = "completed"
    case archived = "archived"
}
