//
// PlanInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PlanInput: Sendable, Codable, Hashable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 50, pattern: nil)
    /** 可選；客戶端可自帶 UUID。僅建立時有效，更新時忽略。 */
    public var id: UUID?
    /** 一般建立必填；from_specs_plan_id 複製模式未帶時沿用範本名 */
    public var name: String?
    public var description: String?
    /** 未帶預設 active */
    public var status: PlanStatus?
    /** 僅建立時有效：整套複製範本（此時 workouts 必須為空） */
    public var fromSpecsPlanId: UUID?
    /** order_index 由陣列順序決定 */
    public var workouts: [PlanWorkoutInput]?

    public init(id: UUID? = nil, name: String? = nil, description: String? = nil, status: PlanStatus? = nil, fromSpecsPlanId: UUID? = nil, workouts: [PlanWorkoutInput]? = nil) {
        self.id = id
        self.name = name
        self.description = description
        self.status = status
        self.fromSpecsPlanId = fromSpecsPlanId
        self.workouts = workouts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case description
        case status
        case fromSpecsPlanId = "from_specs_plan_id"
        case workouts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(fromSpecsPlanId, forKey: .fromSpecsPlanId)
        try container.encodeIfPresent(workouts, forKey: .workouts)
    }
}


extension PlanInput: Identifiable {}
