//
// PlanWorkoutInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PlanWorkoutInput: Sendable, Codable, Hashable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 50, pattern: nil)
    /** 可選；客戶端可自帶 UUID。僅建立時有效。 */
    public var id: UUID?
    public var name: String?
    /** 未帶預設 not_started */
    public var status: PlanWorkoutStatus?
    public var date: String?
    /** 僅建立時有效：從範本積木複製（此時 sets 必須為空） */
    public var fromSpecsPlanWorkoutId: UUID?
    public var sets: [TargetSetInput]?

    public init(id: UUID? = nil, name: String? = nil, status: PlanWorkoutStatus? = nil, date: String? = nil, fromSpecsPlanWorkoutId: UUID? = nil, sets: [TargetSetInput]? = nil) {
        self.id = id
        self.name = name
        self.status = status
        self.date = date
        self.fromSpecsPlanWorkoutId = fromSpecsPlanWorkoutId
        self.sets = sets
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case status
        case date
        case fromSpecsPlanWorkoutId = "from_specs_plan_workout_id"
        case sets
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(fromSpecsPlanWorkoutId, forKey: .fromSpecsPlanWorkoutId)
        try container.encodeIfPresent(sets, forKey: .sets)
    }
}


extension PlanWorkoutInput: Identifiable {}
