//
// PlanWorkoutStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** 訓練計劃狀態（循環菜單全 done 繞回時由 app 重設 not_started） */
public enum PlanWorkoutStatus: String, Sendable, Codable, CaseIterable {
    case notStarted = "not_started"
    case done = "done"
    case skipped = "skipped"
}
