//
// SpecsPlanWorkout.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SpecsPlanWorkout: Sendable, Codable, Hashable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 50, pattern: nil)
    public static let orderIndexRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var id: UUID
    /** null＝獨立範本積木 */
    public var specsPlanId: UUID?
    public var name: String?
    public var orderIndex: Int
    public var createdBy: UUID
    public var createdAt: Date
    public var updatedAt: Date
    public var sets: [TargetSet]

    public init(id: UUID, specsPlanId: UUID?, name: String?, orderIndex: Int, createdBy: UUID, createdAt: Date, updatedAt: Date, sets: [TargetSet]) {
        self.id = id
        self.specsPlanId = specsPlanId
        self.name = name
        self.orderIndex = orderIndex
        self.createdBy = createdBy
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.sets = sets
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case specsPlanId = "specs_plan_id"
        case name
        case orderIndex = "order_index"
        case createdBy = "created_by"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case sets
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(specsPlanId, forKey: .specsPlanId)
        try container.encode(name, forKey: .name)
        try container.encode(orderIndex, forKey: .orderIndex)
        try container.encode(createdBy, forKey: .createdBy)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(sets, forKey: .sets)
    }
}


extension SpecsPlanWorkout: Identifiable {}
