//
// SpecsPlanInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SpecsPlanInput: Sendable, Codable, Hashable {

    public static let nameRule = StringRule(minLength: 1, maxLength: 50, pattern: nil)
    /** 可選；客戶端可自帶 UUID。僅建立時有效，更新時忽略。 */
    public var id: UUID?
    public var name: String
    public var description: String?
    /** order_index 由陣列順序決定 */
    public var workouts: [SpecsPlanWorkoutInput]

    public init(id: UUID? = nil, name: String, description: String? = nil, workouts: [SpecsPlanWorkoutInput]) {
        self.id = id
        self.name = name
        self.description = description
        self.workouts = workouts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case description
        case workouts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(workouts, forKey: .workouts)
    }
}


extension SpecsPlanInput: Identifiable {}
