//
// SpecsPlan.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SpecsPlan: Sendable, Codable, Hashable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 50, pattern: nil)
    public var id: UUID
    public var name: String
    public var description: String?
    public var createdBy: UUID
    public var createdAt: Date
    public var updatedAt: Date
    /** 依 order_index 排序 */
    public var workouts: [SpecsPlanWorkout]

    public init(id: UUID, name: String, description: String?, createdBy: UUID, createdAt: Date, updatedAt: Date, workouts: [SpecsPlanWorkout]) {
        self.id = id
        self.name = name
        self.description = description
        self.createdBy = createdBy
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.workouts = workouts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case description
        case createdBy = "created_by"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case workouts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(description, forKey: .description)
        try container.encode(createdBy, forKey: .createdBy)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(workouts, forKey: .workouts)
    }
}


extension SpecsPlan: Identifiable {}
