//
// TargetSetInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TargetSetInput: Sendable, Codable, Hashable {

    public static let exerciseIndexRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let setIndexRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let targetRepsRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let restSecRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** 可選；客戶端可自帶 UUID。 */
    public var id: UUID?
    public var exerciseId: UUID
    public var exerciseIndex: Int
    public var setIndex: Int
    public var targetWeight: Weight?
    public var targetReps: Int?
    public var restSec: Int?

    public init(id: UUID? = nil, exerciseId: UUID, exerciseIndex: Int, setIndex: Int, targetWeight: Weight? = nil, targetReps: Int? = nil, restSec: Int? = nil) {
        self.id = id
        self.exerciseId = exerciseId
        self.exerciseIndex = exerciseIndex
        self.setIndex = setIndex
        self.targetWeight = targetWeight
        self.targetReps = targetReps
        self.restSec = restSec
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case exerciseId = "exercise_id"
        case exerciseIndex = "exercise_index"
        case setIndex = "set_index"
        case targetWeight = "target_weight"
        case targetReps = "target_reps"
        case restSec = "rest_sec"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(exerciseId, forKey: .exerciseId)
        try container.encode(exerciseIndex, forKey: .exerciseIndex)
        try container.encode(setIndex, forKey: .setIndex)
        try container.encodeIfPresent(targetWeight, forKey: .targetWeight)
        try container.encodeIfPresent(targetReps, forKey: .targetReps)
        try container.encodeIfPresent(restSec, forKey: .restSec)
    }
}


extension TargetSetInput: Identifiable {}
