//
// TargetSet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** 範本內每組目標一列；(exercise_index, set_index) 皆 0-based，同 exercise_index＝同一動作區塊。 */
public struct TargetSet: Sendable, Codable, Hashable {

    public static let exerciseIndexRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let setIndexRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var id: UUID
    public var exerciseId: UUID
    public var exerciseIndex: Int
    public var setIndex: Int
    public var targetWeight: Weight?
    public var targetReps: Int?
    public var restSec: Int?
    public var createdAt: Date

    public init(id: UUID, exerciseId: UUID, exerciseIndex: Int, setIndex: Int, targetWeight: Weight?, targetReps: Int?, restSec: Int?, createdAt: Date) {
        self.id = id
        self.exerciseId = exerciseId
        self.exerciseIndex = exerciseIndex
        self.setIndex = setIndex
        self.targetWeight = targetWeight
        self.targetReps = targetReps
        self.restSec = restSec
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case exerciseId = "exercise_id"
        case exerciseIndex = "exercise_index"
        case setIndex = "set_index"
        case targetWeight = "target_weight"
        case targetReps = "target_reps"
        case restSec = "rest_sec"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(exerciseId, forKey: .exerciseId)
        try container.encode(exerciseIndex, forKey: .exerciseIndex)
        try container.encode(setIndex, forKey: .setIndex)
        try container.encode(targetWeight, forKey: .targetWeight)
        try container.encode(targetReps, forKey: .targetReps)
        try container.encode(restSec, forKey: .restSec)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


extension TargetSet: Identifiable {}
