//
// Weight.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** 重量（存輸入當下單位為真實來源；kg/lb 換算只在顯示層） */
public struct Weight: Sendable, Codable, Hashable {

    public enum Unit: String, Sendable, Codable, CaseIterable {
        case kg = "kg"
        case lb = "lb"
    }
    public static let valueRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: 9999.99, exclusiveMaximum: false, multipleOf: nil)
    public var value: Double
    public var unit: Unit

    public init(value: Double, unit: Unit) {
        self.value = value
        self.unit = unit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case unit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(value, forKey: .value)
        try container.encode(unit, forKey: .unit)
    }
}

