//
// WorkoutSetStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** 每組實際執行狀態 */
public enum WorkoutSetStatus: String, Sendable, Codable, CaseIterable {
    case done = "done"
    case skipped = "skipped"
    case interrupted = "interrupted"
}
