//
// Workout.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Workout: Sendable, Codable, Hashable {

    public static let overallFeelingRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 5, exclusiveMaximum: false, multipleOf: nil)
    public var id: UUID
    public var userId: UUID
    /** 照哪個排課做；來源被刪時由 DB 設回 null */
    public var planWorkoutId: UUID?
    public var date: String
    public var startedAt: Date?
    public var endedAt: Date?
    public var overallFeeling: Int?
    public var note: String?
    public var createdAt: Date
    public var updatedAt: Date
    /** 依 exercise_index, set_index 排序 */
    public var sets: [WorkoutSet]

    public init(id: UUID, userId: UUID, planWorkoutId: UUID?, date: String, startedAt: Date?, endedAt: Date?, overallFeeling: Int?, note: String?, createdAt: Date, updatedAt: Date, sets: [WorkoutSet]) {
        self.id = id
        self.userId = userId
        self.planWorkoutId = planWorkoutId
        self.date = date
        self.startedAt = startedAt
        self.endedAt = endedAt
        self.overallFeeling = overallFeeling
        self.note = note
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.sets = sets
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case userId = "user_id"
        case planWorkoutId = "plan_workout_id"
        case date
        case startedAt = "started_at"
        case endedAt = "ended_at"
        case overallFeeling = "overall_feeling"
        case note
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case sets
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(userId, forKey: .userId)
        try container.encode(planWorkoutId, forKey: .planWorkoutId)
        try container.encode(date, forKey: .date)
        try container.encode(startedAt, forKey: .startedAt)
        try container.encode(endedAt, forKey: .endedAt)
        try container.encode(overallFeeling, forKey: .overallFeeling)
        try container.encode(note, forKey: .note)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(sets, forKey: .sets)
    }
}


extension Workout: Identifiable {}
