//
// WorkoutSetInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct WorkoutSetInput: Sendable, Codable, Hashable {

    public static let exerciseIndexRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let setIndexRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let repsRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let targetRepsRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** 可選；客戶端可自帶 UUID。 */
    public var id: UUID?
    public var exerciseId: UUID
    public var exerciseIndex: Int
    public var setIndex: Int
    public var weight: Weight
    public var reps: Int
    /** 未帶預設 done */
    public var status: WorkoutSetStatus?
    public var fromPlanSetId: UUID?
    public var targetWeight: Weight?
    public var targetReps: Int?

    public init(id: UUID? = nil, exerciseId: UUID, exerciseIndex: Int, setIndex: Int, weight: Weight, reps: Int, status: WorkoutSetStatus? = nil, fromPlanSetId: UUID? = nil, targetWeight: Weight? = nil, targetReps: Int? = nil) {
        self.id = id
        self.exerciseId = exerciseId
        self.exerciseIndex = exerciseIndex
        self.setIndex = setIndex
        self.weight = weight
        self.reps = reps
        self.status = status
        self.fromPlanSetId = fromPlanSetId
        self.targetWeight = targetWeight
        self.targetReps = targetReps
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case exerciseId = "exercise_id"
        case exerciseIndex = "exercise_index"
        case setIndex = "set_index"
        case weight
        case reps
        case status
        case fromPlanSetId = "from_plan_set_id"
        case targetWeight = "target_weight"
        case targetReps = "target_reps"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(exerciseId, forKey: .exerciseId)
        try container.encode(exerciseIndex, forKey: .exerciseIndex)
        try container.encode(setIndex, forKey: .setIndex)
        try container.encode(weight, forKey: .weight)
        try container.encode(reps, forKey: .reps)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(fromPlanSetId, forKey: .fromPlanSetId)
        try container.encodeIfPresent(targetWeight, forKey: .targetWeight)
        try container.encodeIfPresent(targetReps, forKey: .targetReps)
    }
}


extension WorkoutSetInput: Identifiable {}
