//
// WorkoutSetHistoryItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** 動作歷史的一列：workout_set + 所屬 workout 的日期 */
public struct WorkoutSetHistoryItem: Sendable, Codable, Hashable {

    public static let exerciseIndexRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let setIndexRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let repsRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var id: UUID
    public var workoutId: UUID
    public var date: Date
    public var exerciseId: UUID
    public var exerciseIndex: Int
    public var setIndex: Int
    public var weight: Weight
    public var reps: Int
    public var status: WorkoutSetStatus
    public var targetWeight: Weight?
    public var targetReps: Int?
    public var createdAt: Date

    public init(id: UUID, workoutId: UUID, date: Date, exerciseId: UUID, exerciseIndex: Int, setIndex: Int, weight: Weight, reps: Int, status: WorkoutSetStatus, targetWeight: Weight?, targetReps: Int?, createdAt: Date) {
        self.id = id
        self.workoutId = workoutId
        self.date = date
        self.exerciseId = exerciseId
        self.exerciseIndex = exerciseIndex
        self.setIndex = setIndex
        self.weight = weight
        self.reps = reps
        self.status = status
        self.targetWeight = targetWeight
        self.targetReps = targetReps
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case workoutId = "workout_id"
        case date
        case exerciseId = "exercise_id"
        case exerciseIndex = "exercise_index"
        case setIndex = "set_index"
        case weight
        case reps
        case status
        case targetWeight = "target_weight"
        case targetReps = "target_reps"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(workoutId, forKey: .workoutId)
        try container.encode(date, forKey: .date)
        try container.encode(exerciseId, forKey: .exerciseId)
        try container.encode(exerciseIndex, forKey: .exerciseIndex)
        try container.encode(setIndex, forKey: .setIndex)
        try container.encode(weight, forKey: .weight)
        try container.encode(reps, forKey: .reps)
        try container.encode(status, forKey: .status)
        try container.encode(targetWeight, forKey: .targetWeight)
        try container.encode(targetReps, forKey: .targetReps)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


extension WorkoutSetHistoryItem: Identifiable {}
