//
// WorkoutInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct WorkoutInput: Sendable, Codable, Hashable {

    public static let overallFeelingRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 5, exclusiveMaximum: false, multipleOf: nil)
    /** 可選；客戶端可自帶 UUID。僅建立時有效，更新時忽略。 */
    public var id: UUID?
    public var planWorkoutId: UUID?
    public var date: Date
    public var startedAt: Date?
    public var endedAt: Date?
    public var overallFeeling: Int?
    public var note: String?
    public var sets: [WorkoutSetInput]?

    public init(id: UUID? = nil, planWorkoutId: UUID? = nil, date: Date, startedAt: Date? = nil, endedAt: Date? = nil, overallFeeling: Int? = nil, note: String? = nil, sets: [WorkoutSetInput]? = nil) {
        self.id = id
        self.planWorkoutId = planWorkoutId
        self.date = date
        self.startedAt = startedAt
        self.endedAt = endedAt
        self.overallFeeling = overallFeeling
        self.note = note
        self.sets = sets
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case planWorkoutId = "plan_workout_id"
        case date
        case startedAt = "started_at"
        case endedAt = "ended_at"
        case overallFeeling = "overall_feeling"
        case note
        case sets
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(planWorkoutId, forKey: .planWorkoutId)
        try container.encode(date, forKey: .date)
        try container.encodeIfPresent(startedAt, forKey: .startedAt)
        try container.encodeIfPresent(endedAt, forKey: .endedAt)
        try container.encodeIfPresent(overallFeeling, forKey: .overallFeeling)
        try container.encodeIfPresent(note, forKey: .note)
        try container.encodeIfPresent(sets, forKey: .sets)
    }
}


extension WorkoutInput: Identifiable {}
