//
// PlanWorkoutsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class PlanWorkoutsAPI {

    /**
     建立單獨排課（整包；或帶 from_specs_plan_workout_id 從範本積木複製）
     
     - parameter planWorkoutInput: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PlanWorkout
     */
    open class func createStandalonePlanWorkout2(planWorkoutInput: PlanWorkoutInput, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) -> PlanWorkout {
        return try await createStandalonePlanWorkout2WithRequestBuilder(planWorkoutInput: planWorkoutInput, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     建立單獨排課（整包；或帶 from_specs_plan_workout_id 從範本積木複製）
     - POST /v1/plan-workouts
     - 帶 from_specs_plan_workout_id 時 sets 必須為空；date 可選（null＝未排日期）。
     - parameter planWorkoutInput: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PlanWorkout> 
     */
    open class func createStandalonePlanWorkout2WithRequestBuilder(planWorkoutInput: PlanWorkoutInput, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<PlanWorkout> {
        let localVariablePath = "/v1/plan-workouts"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: planWorkoutInput, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PlanWorkout>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     刪除訓練計劃（級聯刪除其 sets）
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deletePlanWorkout(id: UUID, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deletePlanWorkoutWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     刪除訓練計劃（級聯刪除其 sets）
     - DELETE /v1/plan-workouts/{id}
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deletePlanWorkoutWithRequestBuilder(id: UUID, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/plan-workouts/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     取得一筆訓練計劃（單獨排課或掛在菜單底下者皆可）
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PlanWorkout
     */
    open class func getPlanWorkout(id: UUID, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) -> PlanWorkout {
        return try await getPlanWorkoutWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     取得一筆訓練計劃（單獨排課或掛在菜單底下者皆可）
     - GET /v1/plan-workouts/{id}
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PlanWorkout> 
     */
    open class func getPlanWorkoutWithRequestBuilder(id: UUID, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<PlanWorkout> {
        var localVariablePath = "/v1/plan-workouts/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PlanWorkout>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     列出單獨排課（僅 plan_id 為 null 者；日期近到遠、無日期在後）
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [PlanWorkout]
     */
    open class func listStandalonePlanWorkouts2(apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) -> [PlanWorkout] {
        return try await listStandalonePlanWorkouts2WithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     列出單獨排課（僅 plan_id 為 null 者；日期近到遠、無日期在後）
     - GET /v1/plan-workouts
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[PlanWorkout]> 
     */
    open class func listStandalonePlanWorkouts2WithRequestBuilder(apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<[PlanWorkout]> {
        let localVariablePath = "/v1/plan-workouts"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[PlanWorkout]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     整包取代 name/status/date 與 sets（標記完成也走這裡）
     
     - parameter id: (path)  
     - parameter planWorkoutInput: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PlanWorkout
     */
    open class func replacePlanWorkout(id: UUID, planWorkoutInput: PlanWorkoutInput, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) -> PlanWorkout {
        return try await replacePlanWorkoutWithRequestBuilder(id: id, planWorkoutInput: planWorkoutInput, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     整包取代 name/status/date 與 sets（標記完成也走這裡）
     - PUT /v1/plan-workouts/{id}
     - 不變更 plan_id / order_index / from_specs_plan_workout_id；結構調整請走 plan 端點。
     - parameter id: (path)  
     - parameter planWorkoutInput: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PlanWorkout> 
     */
    open class func replacePlanWorkoutWithRequestBuilder(id: UUID, planWorkoutInput: PlanWorkoutInput, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<PlanWorkout> {
        var localVariablePath = "/v1/plan-workouts/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: planWorkoutInput, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PlanWorkout>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
