//
// PlansAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class PlansAPI {

    /**
     建立個人菜單（整包；或帶 from_specs_plan_id 從範本整套複製）
     
     - parameter planInput: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Plan
     */
    open class func createPlan(planInput: PlanInput, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) -> Plan {
        return try await createPlanWithRequestBuilder(planInput: planInput, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     建立個人菜單（整包；或帶 from_specs_plan_id 從範本整套複製）
     - POST /v1/plans
     - 兩種模式： 1. **整包建立**：帶 name + workouts（結構同範本層，另可帶各 workout 的 status/date）。 2. **從範本複製**：帶 from_specs_plan_id（此時 workouts 必須為空）；    name/description 未帶時沿用範本，所有 workout status 歸零為 not_started，    並記錄 from_specs_plan_id / from_specs_plan_workout_id 來源。 
     - parameter planInput: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Plan> 
     */
    open class func createPlanWithRequestBuilder(planInput: PlanInput, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<Plan> {
        let localVariablePath = "/v1/plans"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: planInput, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Plan>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     刪除菜單（級聯刪除其 workouts / sets）
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deletePlan(id: UUID, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deletePlanWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     刪除菜單（級聯刪除其 workouts / sets）
     - DELETE /v1/plans/{id}
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deletePlanWithRequestBuilder(id: UUID, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/plans/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     取得完整菜單（含 workouts / sets）
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Plan
     */
    open class func getPlan(id: UUID, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) -> Plan {
        return try await getPlanWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     取得完整菜單（含 workouts / sets）
     - GET /v1/plans/{id}
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Plan> 
     */
    open class func getPlanWithRequestBuilder(id: UUID, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<Plan> {
        var localVariablePath = "/v1/plans/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Plan>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     列出個人菜單（僅 header；可依 status 過濾，建立時間新到舊）
     
     - parameter status: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [PlanSummary]
     */
    open class func listPlans(status: PlanStatus? = nil, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) -> [PlanSummary] {
        return try await listPlansWithRequestBuilder(status: status, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     列出個人菜單（僅 header；可依 status 過濾，建立時間新到舊）
     - GET /v1/plans
     - parameter status: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[PlanSummary]> 
     */
    open class func listPlansWithRequestBuilder(status: PlanStatus? = nil, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<[PlanSummary]> {
        let localVariablePath = "/v1/plans"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "status": (wrappedValue: status?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[PlanSummary]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     整包取代菜單（header + workouts/sets 全數重建；客戶端送完整狀態）
     
     - parameter id: (path)  
     - parameter planInput: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Plan
     */
    open class func replacePlan(id: UUID, planInput: PlanInput, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) -> Plan {
        return try await replacePlanWithRequestBuilder(id: id, planInput: planInput, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     整包取代菜單（header + workouts/sets 全數重建；客戶端送完整狀態）
     - PUT /v1/plans/{id}
     - from_specs_plan_id 僅建立時有效，帶入會回 400；DB 原值保留不變。
     - parameter id: (path)  
     - parameter planInput: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Plan> 
     */
    open class func replacePlanWithRequestBuilder(id: UUID, planInput: PlanInput, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<Plan> {
        var localVariablePath = "/v1/plans/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: planInput, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Plan>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
