//
// SpecsPlansAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class SpecsPlansAPI {

    /**
     建立菜單範本（aggregate：plan + workouts + sets 整包）
     
     - parameter specsPlanInput: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SpecsPlan
     */
    open class func createPlanTemplate(specsPlanInput: SpecsPlanInput, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) -> SpecsPlan {
        return try await createPlanTemplateWithRequestBuilder(specsPlanInput: specsPlanInput, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     建立菜單範本（aggregate：plan + workouts + sets 整包）
     - POST /v1/specs/plans
     - workouts 的 order_index 由陣列順序決定；sets 的 exercise_index / set_index 由客戶端指派（0-based，不可重複）。
     - parameter specsPlanInput: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SpecsPlan> 
     */
    open class func createPlanTemplateWithRequestBuilder(specsPlanInput: SpecsPlanInput, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<SpecsPlan> {
        let localVariablePath = "/v1/specs/plans"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: specsPlanInput, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SpecsPlan>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     刪除範本（級聯刪除其 workouts / sets）
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deletePlanTemplate(id: UUID, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deletePlanTemplateWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     刪除範本（級聯刪除其 workouts / sets）
     - DELETE /v1/specs/plans/{id}
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deletePlanTemplateWithRequestBuilder(id: UUID, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/specs/plans/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     取得完整範本（含 workouts / sets）
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SpecsPlan
     */
    open class func getPlanTemplate(id: UUID, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) -> SpecsPlan {
        return try await getPlanTemplateWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     取得完整範本（含 workouts / sets）
     - GET /v1/specs/plans/{id}
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SpecsPlan> 
     */
    open class func getPlanTemplateWithRequestBuilder(id: UUID, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<SpecsPlan> {
        var localVariablePath = "/v1/specs/plans/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SpecsPlan>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     列出菜單範本（僅 header，不含 workouts）
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [SpecsPlanSummary]
     */
    open class func listPlanTemplates(apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) -> [SpecsPlanSummary] {
        return try await listPlanTemplatesWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     列出菜單範本（僅 header，不含 workouts）
     - GET /v1/specs/plans
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[SpecsPlanSummary]> 
     */
    open class func listPlanTemplatesWithRequestBuilder(apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<[SpecsPlanSummary]> {
        let localVariablePath = "/v1/specs/plans"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[SpecsPlanSummary]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     整包取代範本（header 更新；workouts / sets 全數重建）
     
     - parameter id: (path)  
     - parameter specsPlanInput: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SpecsPlan
     */
    open class func replacePlanTemplate(id: UUID, specsPlanInput: SpecsPlanInput, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) -> SpecsPlan {
        return try await replacePlanTemplateWithRequestBuilder(id: id, specsPlanInput: specsPlanInput, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     整包取代範本（header 更新；workouts / sets 全數重建）
     - PUT /v1/specs/plans/{id}
     - parameter id: (path)  
     - parameter specsPlanInput: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SpecsPlan> 
     */
    open class func replacePlanTemplateWithRequestBuilder(id: UUID, specsPlanInput: SpecsPlanInput, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<SpecsPlan> {
        var localVariablePath = "/v1/specs/plans/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: specsPlanInput, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SpecsPlan>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
