//
// SpecsExercisesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class SpecsExercisesAPI {

    /**
     建立動作
     
     - parameter exerciseInput: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Exercise
     */
    open class func createExercise(exerciseInput: ExerciseInput, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) -> Exercise {
        return try await createExerciseWithRequestBuilder(exerciseInput: exerciseInput, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     建立動作
     - POST /v1/specs/exercises
     - parameter exerciseInput: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Exercise> 
     */
    open class func createExerciseWithRequestBuilder(exerciseInput: ExerciseInput, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<Exercise> {
        let localVariablePath = "/v1/specs/exercises"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: exerciseInput, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Exercise>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     刪除動作
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteExercise(id: UUID, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteExerciseWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     刪除動作
     - DELETE /v1/specs/exercises/{id}
     - 動作被任何 plan / workout 引用時無法刪除（409，code=in_use）；需先解除引用。
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteExerciseWithRequestBuilder(id: UUID, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/specs/exercises/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     取得單一動作
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Exercise
     */
    open class func getExercise(id: UUID, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) -> Exercise {
        return try await getExerciseWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     取得單一動作
     - GET /v1/specs/exercises/{id}
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Exercise> 
     */
    open class func getExerciseWithRequestBuilder(id: UUID, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<Exercise> {
        var localVariablePath = "/v1/specs/exercises/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Exercise>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     列出動作（可依肌群過濾，依名稱排序）
     
     - parameter muscleGroup: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [Exercise]
     */
    open class func listExercises(muscleGroup: MuscleGroup? = nil, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) -> [Exercise] {
        return try await listExercisesWithRequestBuilder(muscleGroup: muscleGroup, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     列出動作（可依肌群過濾，依名稱排序）
     - GET /v1/specs/exercises
     - parameter muscleGroup: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[Exercise]> 
     */
    open class func listExercisesWithRequestBuilder(muscleGroup: MuscleGroup? = nil, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<[Exercise]> {
        let localVariablePath = "/v1/specs/exercises"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "muscle_group": (wrappedValue: muscleGroup?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Exercise]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     更新動作（整筆取代 name / muscle_group / description）
     
     - parameter id: (path)  
     - parameter exerciseInput: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Exercise
     */
    open class func updateExercise(id: UUID, exerciseInput: ExerciseInput, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) -> Exercise {
        return try await updateExerciseWithRequestBuilder(id: id, exerciseInput: exerciseInput, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     更新動作（整筆取代 name / muscle_group / description）
     - PUT /v1/specs/exercises/{id}
     - parameter id: (path)  
     - parameter exerciseInput: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Exercise> 
     */
    open class func updateExerciseWithRequestBuilder(id: UUID, exerciseInput: ExerciseInput, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<Exercise> {
        var localVariablePath = "/v1/specs/exercises/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: exerciseInput, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Exercise>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
