//
// SpecsPlanWorkoutsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class SpecsPlanWorkoutsAPI {

    /**
     建立獨立訓練範本積木（workout + sets 整包；specs_plan_id 固定為 null）
     
     - parameter specsPlanWorkoutInput: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SpecsPlanWorkout
     */
    open class func createStandalonePlanWorkout(specsPlanWorkoutInput: SpecsPlanWorkoutInput, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) -> SpecsPlanWorkout {
        return try await createStandalonePlanWorkoutWithRequestBuilder(specsPlanWorkoutInput: specsPlanWorkoutInput, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     建立獨立訓練範本積木（workout + sets 整包；specs_plan_id 固定為 null）
     - POST /v1/specs/plan-workouts
     - parameter specsPlanWorkoutInput: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SpecsPlanWorkout> 
     */
    open class func createStandalonePlanWorkoutWithRequestBuilder(specsPlanWorkoutInput: SpecsPlanWorkoutInput, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<SpecsPlanWorkout> {
        let localVariablePath = "/v1/specs/plan-workouts"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: specsPlanWorkoutInput, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SpecsPlanWorkout>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     刪除訓練範本（級聯刪除其 sets）
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deletePlanWorkoutTemplate(id: UUID, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deletePlanWorkoutTemplateWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     刪除訓練範本（級聯刪除其 sets）
     - DELETE /v1/specs/plan-workouts/{id}
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deletePlanWorkoutTemplateWithRequestBuilder(id: UUID, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/specs/plan-workouts/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     取得訓練範本（獨立積木或掛在 plan 底下者皆可）
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SpecsPlanWorkout
     */
    open class func getPlanWorkoutTemplate(id: UUID, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) -> SpecsPlanWorkout {
        return try await getPlanWorkoutTemplateWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     取得訓練範本（獨立積木或掛在 plan 底下者皆可）
     - GET /v1/specs/plan-workouts/{id}
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SpecsPlanWorkout> 
     */
    open class func getPlanWorkoutTemplateWithRequestBuilder(id: UUID, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<SpecsPlanWorkout> {
        var localVariablePath = "/v1/specs/plan-workouts/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SpecsPlanWorkout>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     列出獨立訓練範本積木（僅 specs_plan_id 為 null 者）
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [SpecsPlanWorkout]
     */
    open class func listStandalonePlanWorkouts(apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) -> [SpecsPlanWorkout] {
        return try await listStandalonePlanWorkoutsWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     列出獨立訓練範本積木（僅 specs_plan_id 為 null 者）
     - GET /v1/specs/plan-workouts
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[SpecsPlanWorkout]> 
     */
    open class func listStandalonePlanWorkoutsWithRequestBuilder(apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<[SpecsPlanWorkout]> {
        let localVariablePath = "/v1/specs/plan-workouts"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[SpecsPlanWorkout]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     整包取代 name 與 sets（不變更 specs_plan_id / order_index）
     
     - parameter id: (path)  
     - parameter specsPlanWorkoutInput: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SpecsPlanWorkout
     */
    open class func replacePlanWorkoutTemplate(id: UUID, specsPlanWorkoutInput: SpecsPlanWorkoutInput, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) -> SpecsPlanWorkout {
        return try await replacePlanWorkoutTemplateWithRequestBuilder(id: id, specsPlanWorkoutInput: specsPlanWorkoutInput, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     整包取代 name 與 sets（不變更 specs_plan_id / order_index）
     - PUT /v1/specs/plan-workouts/{id}
     - parameter id: (path)  
     - parameter specsPlanWorkoutInput: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SpecsPlanWorkout> 
     */
    open class func replacePlanWorkoutTemplateWithRequestBuilder(id: UUID, specsPlanWorkoutInput: SpecsPlanWorkoutInput, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<SpecsPlanWorkout> {
        var localVariablePath = "/v1/specs/plan-workouts/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: specsPlanWorkoutInput, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SpecsPlanWorkout>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
