//
// SystemAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class SystemAPI {

    /**
     健康檢查（含 DB 連線）
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetHealth200Response
     */
    open class func getHealth(apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) -> GetHealth200Response {
        return try await getHealthWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     健康檢查（含 DB 連線）
     - GET /healthz
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetHealth200Response> 
     */
    open class func getHealthWithRequestBuilder(apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<GetHealth200Response> {
        let localVariablePath = "/healthz"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetHealth200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
