//
// WorkoutSetsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class WorkoutSetsAPI {

    /**
     某動作的歷史組數（date 新到舊）
     
     - parameter exerciseId: (query)  
     - parameter limit: (query)  (optional, default to 50)
     - parameter offset: (query)  (optional, default to 0)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [WorkoutSetHistoryItem]
     */
    open class func listWorkoutSetsByExercise(exerciseId: UUID, limit: Int? = nil, offset: Int? = nil, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) async throws(ErrorResponse) -> [WorkoutSetHistoryItem] {
        return try await listWorkoutSetsByExerciseWithRequestBuilder(exerciseId: exerciseId, limit: limit, offset: offset, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     某動作的歷史組數（date 新到舊）
     - GET /v1/workout-sets
     - 讀取可細的查詢端點：workout_sets WHERE exercise_id（單表索引查詢，附所屬 workout 日期）。
     - parameter exerciseId: (query)  
     - parameter limit: (query)  (optional, default to 50)
     - parameter offset: (query)  (optional, default to 0)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[WorkoutSetHistoryItem]> 
     */
    open class func listWorkoutSetsByExerciseWithRequestBuilder(exerciseId: UUID, limit: Int? = nil, offset: Int? = nil, apiConfiguration: TrainingLaClientAPIConfiguration = TrainingLaClientAPIConfiguration.shared) -> RequestBuilder<[WorkoutSetHistoryItem]> {
        let localVariablePath = "/v1/workout-sets"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "exercise_id": (wrappedValue: exerciseId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "offset": (wrappedValue: offset?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[WorkoutSetHistoryItem]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
